# Generated by Django 5.1.2 on 2025-02-19 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=255)),
                ('quantidade_peso', models.FloatField()),
                ('preco', models.FloatField()),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.nota')),
            ],
        ),
    ]
